const SHOP_DATA = {
  paintings: {
    id: 1,
    title: "Paintings",
    routeName: "hats",
    items: [
      {
        id: 2,
        name: "Mandizi",
        imageUrl: "https://i.ibb.co/JcwYyq1/banana.jpg",
        description: "",
        price: 18,
      },
      {
        id: 9,
        name: "Two sparrows",
        imageUrl: "https://i.ibb.co/vC9TWKd/two-sparrows.jpg",
        description: "",
        price: 16,
      },
      {
        id: 3,
        name: "The Streets",
        imageUrl: "https://i.ibb.co/dp8xNFg/kipchoge-nganya.jpg",
        description:
          "This painting depicts a busy street in Nairobi, it also presents the picture of the great kenyan marathon runner Eliud Kipchoge, as a graphiti on the matatu",
        price: 35,
      },
      {
        id: 4,
        name: "Darajani",
        imageUrl: "https://i.ibb.co/VmP8pM9/darajani.jpg",
        description:
          "Curious on lookers on the bridge bring a great suspense to the painting arousing curiousity in the viewer. ",
        price: 25,
      },
      {
        id: 5,
        name: "Street Tailor",
        imageUrl: "https://i.ibb.co/SKzPKZD/the-street-tailor.jpg",
        description:
          "A tailor sits on the street as He waits for clients. The painting brings out the wait in the faces of both the tailor and the adjuscent man ",
        price: 18,
      },
      {
        id: 6,
        name: "Maoni Dirishani",
        imageUrl: "https://i.ibb.co/94LZLR6/maoni-dirishani.jpg",
        description:
          "It shows a group following keenly on the proceedings of a meeting, them being outside and most of them being women passes the theme of their exclusion from such events",

        price: 14,
      },
      {
        id: 7,
        name: "Kamukunji",
        imageUrl: "https://i.ibb.co/jL6WhS7/kamukunji.jpg",
        description: "",
        price: 18,
      },
      {
        id: 1,
        name: "Embe Dodo",
        imageUrl: "https://i.ibb.co/StqBTMV/mango.jpg",
        price: 25,
        description:
          "This painting depicts the famous sweet mangoes from the coast of Kenya. It was popularized by a song by the Mushrooms called Embe Dodo released in 2008",
      },
      {
        id: 8,
        name: "Forest Road",
        imageUrl: "https://i.ibb.co/31n1g2T/abstract-forest-road.jpg",
        description: "",
        price: 14,
      },

      {
        id: 101,
        name: "Face of Abstraction",
        imageUrl: "https://i.ibb.co/yqrKjrR/face-of-abstraction.jpg",
        description: "",
        price: 16,
      },
    ],
  },
  drawings: {
    id: 2,
    title: "Drawings",
    routeName: "sneakers",
    items: [
      {
        id: 10,
        name: "Discernment",
        imageUrl: " https://i.ibb.co/GHtb8cP/eye.jpg",
        description: "",
        price: 220,
      },
      {
        id: 11,
        name: "The vase",
        imageUrl: "https://i.ibb.co/r5khzBc/flower-vase.jpg",
        description: "",
        price: 280,
      },
      {
        id: 12,
        name: "Lamp Still-life",
        imageUrl: "https://i.ibb.co/FXSx3CJ/glass-lamp.jpg",
        description: "",
        price: 110,
      },
      {
        id: 13,
        name: "Brick House",
        imageUrl: "https://i.ibb.co/0tBSQT2/house.jpg",
        description: "",
        price: 160,
      },
      {
        id: 14,
        name: "Kitchen table",
        imageUrl: "https://i.ibb.co/pZ9XRTC/kettle.jpg",
        description: "",
        price: 160,
      },
      {
        id: 15,
        name: "Fruit Still-life",
        imageUrl: "https://i.ibb.co/QksXFpp/peper.jpg",
        description: "",
        price: 160,
      },
      {
        id: 16,
        name: "The Street Performer",
        imageUrl: "https://i.ibb.co/cD39qXg/performer.jpg",
        description: "",
        price: 190,
      },
      {
        id: 17,
        name: "Puppy",
        imageUrl: "https://i.ibb.co/rsBsCCN/puppy.jpg",
        description: "",
        price: 200,
      },
      {
        id: 174,
        name: "Air Force 1",
        imageUrl: "https://i.ibb.co/mCwxWGL/Air-Force1.jpg",
        description: "",
        price: 200,
      },
    ],
  },
  crayons: {
    id: 3,
    title: "Crayons",
    routeName: "jackets",
    items: [
      {
        id: 18,
        name: "Black Jean Shearling",
        imageUrl: "https://i.ibb.co/XzcwL5s/black-shearling.png",
        description: "",
        price: 125,
      },
      {
        id: 19,
        name: "Blue Jean Jacket",
        imageUrl: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
        description: "",
        price: 90,
      },
      {
        id: 20,
        name: "Grey Jean Jacket",
        imageUrl: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
        description: "",
        price: 90,
      },
      {
        id: 21,
        name: "Brown Shearling",
        imageUrl: "https://i.ibb.co/s96FpdP/brown-shearling.png",
        description: "",
        price: 165,
      },
      {
        id: 22,
        name: "Tan Trench",
        imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
        description: "",
        price: 185,
      },
    ],
  },
  prints: {
    id: 4,
    title: "Prints",
    routeName: "womens",
    items: [
      {
        id: 23,
        name: "Blue Tanktop",
        imageUrl: "https://i.ibb.co/7CQVJNm/blue-tank.png",
        description: "",
        price: 25,
      },
      {
        id: 24,
        name: "Floral Blouse",
        imageUrl: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
        description: "",
        price: 20,
      },
      {
        id: 25,
        name: "Floral Dress",
        imageUrl: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
        description: "",
        price: 80,
      },
      {
        id: 26,
        name: "Red Dots Dress",
        imageUrl: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
        description: "",
        price: 80,
      },
      {
        id: 27,
        name: "Striped Sweater",
        imageUrl: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
        description: "",
        price: 45,
      },
      {
        id: 28,
        name: "Yellow Track Suit",
        imageUrl: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
        description: "",
        price: 135,
      },
      {
        id: 29,
        name: "White Blouse",
        imageUrl: "https://i.ibb.co/qBcrsJg/white-vest.png",
        description: "",
        price: 20,
      },
    ],
  },
  sketches: {
    id: 5,
    title: "Sketches",
    routeName: "mens",
    items: [
      {
        id: 30,
        name: "Camo Down Vest",
        imageUrl: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
        description: "",
        price: 325,
      },
      {
        id: 31,
        name: "Floral T-shirt",
        imageUrl: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
        description: "",
        price: 20,
      },
      {
        id: 32,
        name: "Black & White Longsleeve",
        imageUrl: "https://i.ibb.co/55z32tw/long-sleeve.png",
        description: "",
        price: 25,
      },
      {
        id: 33,
        name: "Pink T-shirt",
        imageUrl: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
        description: "",
        price: 25,
      },
      {
        id: 34,
        name: "Jean Long Sleeve",
        imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
        description: "",
        price: 40,
      },
      {
        id: 35,
        name: "Burgundy T-shirt",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        description: "",
        price: 25,
      },
    ],
  },
};

export default SHOP_DATA;
